name: Sync Upstream
 
on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
 
      # --- GIT CONFIGURATION AND REMOTE SETUP ---
      - name: Set up Git User Identity
        run: |
          # The bot identity for the new merge commit
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
    
      - name: Add upstream remote and fetch
        run: |
          # Add the upstream remote reference
          # NOTE: Replace the URL below with the actual original repository if this is wrong.
          git remote add upstream https://github.com/Aparnaa-Marimuthu/my-app.git
          
          # Fetch all branches from the upstream remote
          git fetch upstream
    
      # --- MERGE AND PUSH ---
      - name: Merge upstream/main into local main
        run: |
          # Ensure we are on the target branch
          git checkout main
          
          # Perform the merge. Using '--no-edit' to prevent Git from opening an editor 
          # which would stall the CI job. '--allow-unrelated-histories' is optional
          # but helpful for the very first merge of a newly forked repo.
          git merge upstream/main --allow-unrelated-histories --no-edit -m "Sync: Merge upstream changes from Aparnaa-Marimuthu/my-app"
          
      - name: Push changes to your repository
        # Use 'origin' which is the default name for your fork's remote.
        # This push uses the token provided by actions/checkout.
        run: git push origin main
     
